export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const GROUP_REPOSITORY = Symbol('GROUP_REPOSITORY');
export const PROMOTION_AI_PROVIDER = Symbol('PROMOTION_AI_PROVIDER');
export const USER_TASTE_REPOSITORY = Symbol('USER_TASTE_REPOSITORY');
export const USER_TASTE_VECTOR_STORE = Symbol('USER_TASTE_VECTOR_STORE');
export const EMBEDDING_PROVIDER = Symbol('EMBEDDING_PROVIDER');
